import { SubcuentaData, SeparacionECDData } from '@/types/process';

export const mockSubcuentas: SubcuentaData[] = [
  {
    id: 'sub-001',
    code: 'C006001',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 10:30', executedBy: 'Carlos García' },
      oferta: { status: 'in-progress', lastUpdate: '2025-12-12 11:05', executedBy: 'María López' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 10:30', executedBy: 'Roberto Hernández' },
      pml_mda: { status: 'error', lastUpdate: '2025-12-12 09:50', executedBy: 'Ana Martínez' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 10:30', executedBy: 'Fernando Ruiz' },
      ecd_dataset: { status: 'pending', executedBy: 'Carlos García' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 10:30', executedBy: 'Patricia Sánchez' },
      tablas_mem: { status: 'in-progress', lastUpdate: '2025-12-12 11:15', executedBy: 'Jorge Ramírez' },
      validacion: { status: 'success', status2: 'in-progress', lastUpdate: '2025-12-12 10:30', executedBy: 'María López', executedBy2: 'Carlos García' },
      mem_vs_monitor: { status: 'success', lastUpdate: '2025-12-12 10:30', executedBy: 'Ana Martínez' },
      revision: { status: 'error', lastUpdate: '2025-12-12 08:20', executedBy: 'Fernando Ruiz' },
    },
  },
  {
    id: 'sub-003',
    code: 'C006003',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'in-progress', lastUpdate: '2025-12-12 09:15', executedBy: 'Patricia Sánchez' },
      oferta: { status: 'error', lastUpdate: '2025-12-12 09:00', executedBy: 'Jorge Ramírez' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 08:30', executedBy: 'Carlos García' },
      pml_mda: { status: 'pending', executedBy: 'María López' },
      pml_mtr: { status: 'error', lastUpdate: '2025-12-12 08:45', executedBy: 'Fernando Ruiz' },
      ecd_dataset: { status: 'in-progress', lastUpdate: '2025-12-12 09:20', executedBy: 'Ana Martínez' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 07:50', executedBy: 'Roberto Hernández' },
      tablas_mem: { status: 'pending', executedBy: 'Patricia Sánchez' },
      validacion: { status: 'success', status2: 'error', lastUpdate: '2025-12-12 08:10', executedBy: 'Jorge Ramírez', executedBy2: 'Ana Martínez' },
      mem_vs_monitor: { status: 'pending', executedBy: 'María López' },
      revision: { status: 'error', status2: 'pending', lastUpdate: '2025-12-12 07:30', executedBy: 'Ana Martínez', executedBy2: 'Patricia Sánchez' },
    },
  },
  {
    id: 'sub-004',
    code: 'C006004',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 10:00', executedBy: 'Roberto Hernández' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 10:05', executedBy: 'Fernando Ruiz' },
      asignacion: { status: 'in-progress', lastUpdate: '2025-12-12 10:40', executedBy: 'Patricia Sánchez' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 09:55', executedBy: 'Jorge Ramírez' },
      pml_mtr: { status: 'error', lastUpdate: '2025-12-12 09:10', executedBy: 'Carlos García' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 10:15', executedBy: 'María López' },
      ecyp: { status: 'pending', executedBy: 'Ana Martínez' },
      tablas_mem: { status: 'success', lastUpdate: '2025-12-12 10:20', executedBy: 'Roberto Hernández' },
      validacion: { status: 'in-progress', status2: 'success', lastUpdate: '2025-12-12 10:50', executedBy: 'Fernando Ruiz', executedBy2: 'Jorge Ramírez' },
      mem_vs_monitor: { status: 'success', lastUpdate: '2025-12-12 10:25', executedBy: 'Jorge Ramírez' },
      revision: { status: 'pending', status2: 'in-progress', executedBy: 'Carlos García', executedBy2: 'María López' },
    },
  },
  {
    id: 'sub-005',
    code: 'C006005',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'pending', executedBy: 'María López' },
      oferta: { status: 'pending', executedBy: 'Ana Martínez' },
      asignacion: { status: 'pending', executedBy: 'Fernando Ruiz' },
      pml_mda: { status: 'in-progress', executedBy: 'Jorge Ramírez' },
      pml_mtr: { status: 'in-progress', executedBy: 'Patricia Sánchez' },
      ecd_dataset: { status: 'pending', executedBy: 'Carlos García' },
      ecyp: { status: 'pending', executedBy: 'Roberto Hernández' },
      tablas_mem: { status: 'pending', executedBy: 'María López' },
      validacion: { status: 'pending', status2: 'pending', executedBy: 'Ana Martínez', executedBy2: 'Fernando Ruiz' },
      mem_vs_monitor: { status: 'pending', executedBy: 'Jorge Ramírez' },
      revision: { status: 'pending', status2: 'pending', executedBy: 'Patricia Sánchez', executedBy2: 'Jorge Ramírez' },
    },
  },
  {
    id: 'sub-006',
    code: 'C006006',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', executedBy: 'Ana Martínez' },
      oferta: { status: 'success', executedBy: 'Carlos García' },
      asignacion: { status: 'success', executedBy: 'María López' },
      pml_mda: { status: 'success', executedBy: 'Roberto Hernández' },
      pml_mtr: { status: 'success', executedBy: 'Fernando Ruiz' },
      ecd_dataset: { status: 'success', executedBy: 'Patricia Sánchez' },
      ecyp: { status: 'success', executedBy: 'Jorge Ramírez' },
      tablas_mem: { status: 'success', executedBy: 'Carlos García' },
      validacion: { status: 'success', status2: 'success', executedBy: 'María López', executedBy2: 'Roberto Hernández' },
      mem_vs_monitor: { status: 'success', executedBy: 'Roberto Hernández' },
      revision: { status: 'success', status2: 'success', executedBy: 'Fernando Ruiz', executedBy2: 'Ana Martínez' },
    },
  },
  {
    id: 'sub-008',
    code: 'C006008',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', executedBy: 'Jorge Ramírez' },
      oferta: { status: 'success', executedBy: 'Patricia Sánchez' },
      asignacion: { status: 'success', executedBy: 'Fernando Ruiz' },
      pml_mda: { status: 'success', executedBy: 'Ana Martínez' },
      pml_mtr: { status: 'success', executedBy: 'Carlos García' },
      ecd_dataset: { status: 'success', executedBy: 'Roberto Hernández' },
      ecyp: { status: 'success', executedBy: 'María López' },
      tablas_mem: { status: 'success', executedBy: 'Jorge Ramírez' },
      validacion: { status: 'success', status2: 'success', executedBy: 'Patricia Sánchez', executedBy2: 'Carlos García' },
      mem_vs_monitor: { status: 'success', executedBy: 'Ana Martínez' },
      revision: { status: 'success', status2: 'success', executedBy: 'María López', executedBy2: 'Jorge Ramírez' },
    },
  },
  {
    id: 'sub-009',
    code: 'C006009',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 07:30', executedBy: 'Luis Mendoza' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 07:45', executedBy: 'Sandra Torres' },
      asignacion: { status: 'in-progress', lastUpdate: '2025-12-12 08:10', executedBy: 'Diego Flores' },
      pml_mda: { status: 'pending', executedBy: 'Gabriela Ríos' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 07:55', executedBy: 'Luis Mendoza' },
      ecd_dataset: { status: 'error', lastUpdate: '2025-12-12 08:00', executedBy: 'Sandra Torres' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 07:40', executedBy: 'Carlos García' },
      tablas_mem: { status: 'pending', executedBy: 'Diego Flores' },
      validacion: { status: 'success', status2: 'pending', lastUpdate: '2025-12-12 07:50', executedBy: 'María López', executedBy2: 'Diego Flores' },
      mem_vs_monitor: { status: 'success', lastUpdate: '2025-12-12 07:35', executedBy: 'Fernando Ruiz' },
      revision: { status: 'pending', status2: 'error', executedBy: 'Ana Martínez', executedBy2: 'Luis Mendoza' },
    },
  },
  {
    id: 'sub-010',
    code: 'C006010',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'error', lastUpdate: '2025-12-12 06:30', executedBy: 'Roberto Hernández' },
      oferta: { status: 'in-progress', lastUpdate: '2025-12-12 09:00', executedBy: 'Patricia Sánchez' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 08:50', executedBy: 'Jorge Ramírez' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 08:55', executedBy: 'Luis Mendoza' },
      pml_mtr: { status: 'pending', executedBy: 'Sandra Torres' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 08:45', executedBy: 'Diego Flores' },
      ecyp: { status: 'error', lastUpdate: '2025-12-12 07:15', executedBy: 'Gabriela Ríos' },
      tablas_mem: { status: 'in-progress', lastUpdate: '2025-12-12 09:10', executedBy: 'Carlos García' },
      validacion: { status: 'pending', status2: 'error', executedBy: 'María López', executedBy2: 'Sandra Torres' },
      mem_vs_monitor: { status: 'success', lastUpdate: '2025-12-12 08:35', executedBy: 'Ana Martínez' },
      revision: { status: 'in-progress', status2: 'success', lastUpdate: '2025-12-12 09:20', executedBy: 'Roberto Hernández', executedBy2: 'Gabriela Ríos' },
    },
  },
  {
    id: 'sub-011',
    code: 'C006011',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 10:00', executedBy: 'Sandra Torres' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 10:05', executedBy: 'Diego Flores' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 10:10', executedBy: 'Gabriela Ríos' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 10:15', executedBy: 'Luis Mendoza' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 10:20', executedBy: 'Patricia Sánchez' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 10:25', executedBy: 'Jorge Ramírez' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 10:30', executedBy: 'Carlos García' },
      tablas_mem: { status: 'success', lastUpdate: '2025-12-12 10:35', executedBy: 'María López' },
      validacion: { status: 'success', status2: 'success', lastUpdate: '2025-12-12 10:40', executedBy: 'Fernando Ruiz', executedBy2: 'Diego Flores' },
      mem_vs_monitor: { status: 'success', lastUpdate: '2025-12-12 10:50', executedBy: 'Roberto Hernández' },
      revision: { status: 'success', status2: 'success', lastUpdate: '2025-12-12 10:55', executedBy: 'Sandra Torres', executedBy2: 'Gabriela Ríos' },
    },
  },
  {
    id: 'sub-012',
    code: 'C006012',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'pending', executedBy: 'Diego Flores' },
      oferta: { status: 'pending', executedBy: 'Gabriela Ríos' },
      asignacion: { status: 'pending', executedBy: 'Luis Mendoza' },
      pml_mda: { status: 'in-progress', lastUpdate: '2025-12-12 11:00', executedBy: 'Sandra Torres' },
      pml_mtr: { status: 'in-progress', lastUpdate: '2025-12-12 11:05', executedBy: 'Carlos García' },
      ecd_dataset: { status: 'pending', executedBy: 'Patricia Sánchez' },
      ecyp: { status: 'pending', executedBy: 'Jorge Ramírez' },
      tablas_mem: { status: 'pending', executedBy: 'Diego Flores' },
      validacion: { status: 'pending', status2: 'pending', executedBy: 'Gabriela Ríos', executedBy2: 'Luis Mendoza' },
      mem_vs_monitor: { status: 'pending', executedBy: 'María López' },
      revision: { status: 'pending', status2: 'pending', executedBy: 'Fernando Ruiz', executedBy2: 'Sandra Torres' },
    },
  },
  {
    id: 'sub-013',
    code: 'C006013',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 09:00', executedBy: 'Gabriela Ríos' },
      oferta: { status: 'error', lastUpdate: '2025-12-12 08:30', executedBy: 'Luis Mendoza' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 09:05', executedBy: 'Sandra Torres' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 09:10', executedBy: 'Diego Flores' },
      pml_mtr: { status: 'in-progress', lastUpdate: '2025-12-12 09:40', executedBy: 'Roberto Hernández' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 09:15', executedBy: 'Patricia Sánchez' },
      ecyp: { status: 'pending', executedBy: 'Jorge Ramírez' },
      tablas_mem: { status: 'success', lastUpdate: '2025-12-12 09:20', executedBy: 'Ana Martínez' },
      validacion: { status: 'error', status2: 'success', lastUpdate: '2025-12-12 08:15', executedBy: 'Carlos García', executedBy2: 'Patricia Sánchez' },
      mem_vs_monitor: { status: 'in-progress', lastUpdate: '2025-12-12 09:45', executedBy: 'Fernando Ruiz' },
      revision: { status: 'success', status2: 'error', lastUpdate: '2025-12-12 09:30', executedBy: 'Gabriela Ríos', executedBy2: 'Luis Mendoza' },
    },
  },
  {
    id: 'sub-014',
    code: 'C006014',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 11:00', executedBy: 'Ana Martínez' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 11:05', executedBy: 'Roberto Hernández' },
      asignacion: { status: 'error', lastUpdate: '2025-12-12 10:20', executedBy: 'Fernando Ruiz' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 11:10', executedBy: 'Patricia Sánchez' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 11:15', executedBy: 'Jorge Ramírez' },
      ecd_dataset: { status: 'in-progress', lastUpdate: '2025-12-12 11:30', executedBy: 'Luis Mendoza' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 11:20', executedBy: 'Sandra Torres' },
      tablas_mem: { status: 'success', lastUpdate: '2025-12-12 11:25', executedBy: 'Diego Flores' },
      validacion: { status: 'success', status2: 'in-progress', lastUpdate: '2025-12-12 11:30', executedBy: 'Gabriela Ríos', executedBy2: 'Diego Flores' },
      mem_vs_monitor: { status: 'success', lastUpdate: '2025-12-12 11:35', executedBy: 'María López' },
      revision: { status: 'success', status2: 'success', lastUpdate: '2025-12-12 11:40', executedBy: 'Ana Martínez', executedBy2: 'Roberto Hernández' },
    },
  },
  {
    id: 'sub-015',
    code: 'C006015',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'in-progress', lastUpdate: '2025-12-12 10:30', executedBy: 'Carlos García' },
      oferta: { status: 'pending', executedBy: 'María López' },
      asignacion: { status: 'in-progress', lastUpdate: '2025-12-12 10:35', executedBy: 'Fernando Ruiz' },
      pml_mda: { status: 'error', lastUpdate: '2025-12-12 09:50', executedBy: 'Ana Martínez' },
      pml_mtr: { status: 'pending', executedBy: 'Roberto Hernández' },
      ecd_dataset: { status: 'in-progress', lastUpdate: '2025-12-12 10:40', executedBy: 'Patricia Sánchez' },
      ecyp: { status: 'pending', executedBy: 'Jorge Ramírez' },
      tablas_mem: { status: 'error', lastUpdate: '2025-12-12 09:30', executedBy: 'Luis Mendoza' },
      validacion: { status: 'pending', status2: 'error', executedBy: 'Sandra Torres', executedBy2: 'Ana Martínez' },
      mem_vs_monitor: { status: 'pending', executedBy: 'Gabriela Ríos' },
      revision: { status: 'error', status2: 'pending', lastUpdate: '2025-12-12 09:15', executedBy: 'Carlos García', executedBy2: 'Fernando Ruiz' },
    },
  },
  {
    id: 'sub-016',
    code: 'C006016',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 08:00', executedBy: 'Sandra Torres' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 08:05', executedBy: 'Diego Flores' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 08:10', executedBy: 'Gabriela Ríos' },
      pml_mda: { status: 'in-progress', lastUpdate: '2025-12-12 08:40', executedBy: 'Luis Mendoza' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 08:15', executedBy: 'Ana Martínez' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 08:20', executedBy: 'Roberto Hernández' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 08:25', executedBy: 'Fernando Ruiz' },
      tablas_mem: { status: 'success', lastUpdate: '2025-12-12 08:30', executedBy: 'Patricia Sánchez' },
      validacion: { status: 'in-progress', status2: 'success', lastUpdate: '2025-12-12 08:45', executedBy: 'Jorge Ramírez', executedBy2: 'Luis Mendoza' },
      mem_vs_monitor: { status: 'success', lastUpdate: '2025-12-12 08:38', executedBy: 'María López' },
      revision: { status: 'success', status2: 'in-progress', lastUpdate: '2025-12-12 08:42', executedBy: 'Sandra Torres', executedBy2: 'Diego Flores' },
    },
  },
  {
    id: 'sub-017',
    code: 'C006017',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 07:00', executedBy: 'Jorge Ramírez' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 07:05', executedBy: 'Carlos García' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 07:10', executedBy: 'María López' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 07:15', executedBy: 'Fernando Ruiz' },
      pml_mtr: { status: 'error', lastUpdate: '2025-12-12 06:45', executedBy: 'Ana Martínez' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 07:20', executedBy: 'Roberto Hernández' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 07:25', executedBy: 'Patricia Sánchez' },
      tablas_mem: { status: 'success', lastUpdate: '2025-12-12 07:30', executedBy: 'Luis Mendoza' },
      validacion: { status: 'success', status2: 'success', lastUpdate: '2025-12-12 07:35', executedBy: 'Sandra Torres', executedBy2: 'Gabriela Ríos' },
      mem_vs_monitor: { status: 'success', lastUpdate: '2025-12-12 07:45', executedBy: 'Gabriela Ríos' },
      revision: { status: 'success', status2: 'success', lastUpdate: '2025-12-12 07:50', executedBy: 'Jorge Ramírez', executedBy2: 'Patricia Sánchez' },
    },
  },
  {
    id: 'sub-018',
    code: 'C006018',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'error', lastUpdate: '2025-12-12 06:00', executedBy: 'Diego Flores' },
      oferta: { status: 'error', lastUpdate: '2025-12-12 06:10', executedBy: 'Gabriela Ríos' },
      asignacion: { status: 'pending', executedBy: 'Luis Mendoza' },
      pml_mda: { status: 'pending', executedBy: 'Sandra Torres' },
      pml_mtr: { status: 'pending', executedBy: 'Carlos García' },
      ecd_dataset: { status: 'pending', executedBy: 'María López' },
      ecyp: { status: 'pending', executedBy: 'Fernando Ruiz' },
      tablas_mem: { status: 'pending', executedBy: 'Ana Martínez' },
      validacion: { status: 'pending', status2: 'pending', executedBy: 'Roberto Hernández', executedBy2: 'María López' },
      mem_vs_monitor: { status: 'pending', executedBy: 'Jorge Ramírez' },
      revision: { status: 'pending', status2: 'pending', executedBy: 'Diego Flores', executedBy2: 'Carlos García' },
    },
  },
  {
    id: 'sub-019',
    code: 'C006019',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 09:30', executedBy: 'Luis Mendoza' },
      oferta: { status: 'in-progress', lastUpdate: '2025-12-12 10:00', executedBy: 'Sandra Torres' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 09:35', executedBy: 'Diego Flores' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 09:40', executedBy: 'Gabriela Ríos' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 09:45', executedBy: 'Ana Martínez' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 09:50', executedBy: 'Roberto Hernández' },
      ecyp: { status: 'in-progress', lastUpdate: '2025-12-12 10:05', executedBy: 'Fernando Ruiz' },
      tablas_mem: { status: 'success', lastUpdate: '2025-12-12 09:55', executedBy: 'Patricia Sánchez' },
      validacion: { status: 'success', status2: 'success', lastUpdate: '2025-12-12 10:00', executedBy: 'Jorge Ramírez', executedBy2: 'Ana Martínez' },
      mem_vs_monitor: { status: 'success', lastUpdate: '2025-12-12 10:10', executedBy: 'María López' },
      revision: { status: 'pending', status2: 'in-progress', executedBy: 'Luis Mendoza', executedBy2: 'Sandra Torres' },
    },
  },
  {
    id: 'sub-020',
    code: 'C006020',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 11:30', executedBy: 'Gabriela Ríos' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 11:35', executedBy: 'Luis Mendoza' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 11:40', executedBy: 'Sandra Torres' },
      pml_mda: { status: 'error', lastUpdate: '2025-12-12 11:00', executedBy: 'Diego Flores' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 11:45', executedBy: 'Carlos García' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 11:50', executedBy: 'María López' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 11:55', executedBy: 'Fernando Ruiz' },
      tablas_mem: { status: 'in-progress', lastUpdate: '2025-12-12 12:00', executedBy: 'Ana Martínez' },
      validacion: { status: 'success', status2: 'error', lastUpdate: '2025-12-12 12:05', executedBy: 'Roberto Hernández', executedBy2: 'Fernando Ruiz' },
      mem_vs_monitor: { status: 'pending', executedBy: 'Jorge Ramírez' },
      revision: { status: 'success', status2: 'in-progress', lastUpdate: '2025-12-12 12:15', executedBy: 'Gabriela Ríos', executedBy2: 'Diego Flores' },
    },
  },
];

export const mockSeparacionECDData: SeparacionECDData = {
  startDate: '12/02/2026',
  endDate: '12/02/2026',
  progress: 65,
  subcuentas: mockSubcuentas,
};

export const procesColumns = [
  { id: 'medicion', label: 'Medición' },
  { id: 'oferta', label: 'Oferta' },
  { id: 'asignacion', label: 'Asignación MDA' },
  { id: 'pml_mda', label: 'PML MDA' },
  { id: 'pml_mtr', label: 'PML MTR' },
  { id: 'ecd_dataset', label: 'ECD Dataset' },
  { id: 'ecyp', label: 'ECyP' },
  { id: 'tablas_mem', label: 'Tablas MEM' },
  { id: 'validacion', label: 'Validación' },

  { id: 'mem_vs_monitor', label: 'MEMvsMonitor' },
  { id: 'revision', label: 'Revisión' },
];
