import { SubcuentaData, SeparacionECDData } from '@/types/process';

export const mockSubcuentas: SubcuentaData[] = [
  {
    id: 'sub-001',
    code: 'C006001',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 10:30', executedBy: 'Carlos García' },
      oferta: { status: 'in-progress', lastUpdate: '2025-12-12 11:05', executedBy: 'María López' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 10:30', executedBy: 'Roberto Hernández' },
      pml_mda: { status: 'error', lastUpdate: '2025-12-12 09:50', executedBy: 'Ana Martínez' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 10:30', executedBy: 'Fernando Ruiz' },
      ecd_dataset: { status: 'pending', executedBy: 'Carlos García' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 10:30', executedBy: 'Patricia Sánchez' },
      seg_med: { status: 'pending' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'in-progress', lastUpdate: '2025-12-12 11:15', executedBy: 'Jorge Ramírez' },
      validacion: { status: 'success', lastUpdate: '2025-12-12 10:30', executedBy: 'María López' },
      vobo_mensual: { status: 'error', lastUpdate: '2025-12-12 08:20', executedBy: 'Fernando Ruiz' },
      revision: { status: 'success' },
    },
    clients: [
      {
        id: 'cli-001-1', name: 'BIC349',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-001-2', name: 'BICCUAUTITLAN',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'pending' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-001-3', name: 'RARIZPE',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'error' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-001-4', name: 'SG206',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'error' },
        },
      },
      {
        id: 'cli-001-5', name: 'SGOBAIN',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
    ],
  },
  {
    id: 'sub-003',
    code: 'C006003',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'in-progress', lastUpdate: '2025-12-12 09:15', executedBy: 'Patricia Sánchez' },
      oferta: { status: 'error', lastUpdate: '2025-12-12 09:00', executedBy: 'Jorge Ramírez' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 08:30', executedBy: 'Carlos García' },
      pml_mda: { status: 'pending', executedBy: 'María López' },
      pml_mtr: { status: 'error', lastUpdate: '2025-12-12 08:45', executedBy: 'Fernando Ruiz' },
      ecd_dataset: { status: 'in-progress', lastUpdate: '2025-12-12 09:20', executedBy: 'Ana Martínez' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 07:50', executedBy: 'Roberto Hernández' },
      seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'pending', executedBy: 'Patricia Sánchez' },
      validacion: { status: 'success', lastUpdate: '2025-12-12 08:10', executedBy: 'Jorge Ramírez' },
      vobo_mensual: { status: 'error', lastUpdate: '2025-12-12 07:30', executedBy: 'Ana Martínez' },
      revision: { status: 'success' },
    },
    clients: [
      {
        id: 'cli-003-1', name: 'CEMEX_NTE',
        columns: {
          medicion: { status: 'in-progress' }, oferta: { status: 'error' }, asignacion: { status: 'success' },
          pml_mda: { status: 'pending' }, pml_mtr: { status: 'error' }, ecd_dataset: { status: 'in-progress' },
          ecyp: { status: 'success' }, seg_med: { status: 'pending' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'pending' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'error' },
          revision: { status: 'pending' },
        },
      },
      {
        id: 'cli-003-2', name: 'CEMEX_SUR',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'pending' },
        },
      },
      {
        id: 'cli-003-3', name: 'VITRO_PTE',
        columns: {
          medicion: { status: 'pending' }, oferta: { status: 'pending' }, asignacion: { status: 'pending' },
          pml_mda: { status: 'pending' }, pml_mtr: { status: 'pending' }, ecd_dataset: { status: 'pending' },
          ecyp: { status: 'pending' }, seg_med: { status: 'error' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'pending' },
          validacion: { status: 'pending' },          vobo_mensual: { status: 'pending' },
          revision: { status: 'in-progress' },
        },
      },
    ],
  },
  {
    id: 'sub-004',
    code: 'C006004',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 10:00', executedBy: 'Roberto Hernández' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 10:05', executedBy: 'Fernando Ruiz' },
      asignacion: { status: 'in-progress', lastUpdate: '2025-12-12 10:40', executedBy: 'Patricia Sánchez' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 09:55', executedBy: 'Jorge Ramírez' },
      pml_mtr: { status: 'error', lastUpdate: '2025-12-12 09:10', executedBy: 'Carlos García' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 10:15', executedBy: 'María López' },
      ecyp: { status: 'pending', executedBy: 'Ana Martínez' },
      seg_med: { status: 'error' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success', lastUpdate: '2025-12-12 10:20', executedBy: 'Roberto Hernández' },
      validacion: { status: 'in-progress', lastUpdate: '2025-12-12 10:50', executedBy: 'Fernando Ruiz' },
      vobo_mensual: { status: 'pending', executedBy: 'Carlos García' },
      revision: { status: 'success' },
    },
    clients: [
      {
        id: 'cli-004-1', name: 'ALFA_NTE',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-004-2', name: 'FEMSA_CTR',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'pending' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'pending' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'in-progress' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'pending' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'pending' },
        },
      },
      {
        id: 'cli-004-3', name: 'BIMBO_SUR',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'error' }, asignacion: { status: 'success' },
          pml_mda: { status: 'in-progress' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'pending' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'error' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'success' },
        },
      },
    ],
  },
  {
    id: 'sub-005',
    code: 'C006005',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'pending', executedBy: 'María López' },
      oferta: { status: 'pending', executedBy: 'Ana Martínez' },
      asignacion: { status: 'pending', executedBy: 'Fernando Ruiz' },
      pml_mda: { status: 'in-progress', executedBy: 'Jorge Ramírez' },
      pml_mtr: { status: 'in-progress', executedBy: 'Patricia Sánchez' },
      ecd_dataset: { status: 'pending', executedBy: 'Carlos García' },
      ecyp: { status: 'pending', executedBy: 'Roberto Hernández' },
      seg_med: { status: 'error' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'pending', executedBy: 'María López' },
      validacion: { status: 'pending', executedBy: 'Ana Martínez' },
      vobo_mensual: { status: 'pending', executedBy: 'Patricia Sánchez' },
      revision: { status: 'in-progress' },
    },
    clients: [
      {
        id: 'cli-005-1', name: 'PEMEX_OCC',
        columns: {
          medicion: { status: 'in-progress' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'in-progress' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'error' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-005-2', name: 'TELMEX_NTE',
        columns: {
          medicion: { status: 'pending' }, oferta: { status: 'pending' }, asignacion: { status: 'success' },
          pml_mda: { status: 'pending' }, pml_mtr: { status: 'pending' }, ecd_dataset: { status: 'pending' },
          ecyp: { status: 'success' }, seg_med: { status: 'pending' }, check_oferta: { status: 'in-progress' }, tablas_mem: { status: 'pending' },
          validacion: { status: 'pending' },          vobo_mensual: { status: 'pending' },
          revision: { status: 'success' },
        },
      },
    ],
  },
  {
    id: 'sub-006',
    code: 'C006006',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', executedBy: 'Ana Martínez' },
      oferta: { status: 'success', executedBy: 'Carlos García' },
      asignacion: { status: 'success', executedBy: 'María López' },
      pml_mda: { status: 'success', executedBy: 'Roberto Hernández' },
      pml_mtr: { status: 'success', executedBy: 'Fernando Ruiz' },
      ecd_dataset: { status: 'success', executedBy: 'Patricia Sánchez' },
      ecyp: { status: 'success', executedBy: 'Jorge Ramírez' },
      seg_med: { status: 'success' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success', executedBy: 'Carlos García' },
      validacion: { status: 'success', executedBy: 'María López' },
      vobo_mensual: { status: 'success', executedBy: 'Fernando Ruiz' },
      revision: { status: 'pending' },
    },
    clients: [
      {
        id: 'cli-006-1', name: 'SORIANA_PTE',
        columns: {
          medicion: { status: 'error' }, oferta: { status: 'success' }, asignacion: { status: 'error' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'error' },
          ecyp: { status: 'success' }, seg_med: { status: 'error' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'error' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-006-2', name: 'MODELO_BCS',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'error' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'pending' },
        },
      },
      {
        id: 'cli-006-3', name: 'COPPEL_CHI',
        columns: {
          medicion: { status: 'in-progress' }, oferta: { status: 'in-progress' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'in-progress' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'in-progress' }, seg_med: { status: 'pending' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'in-progress' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'error' },
        },
      },
      {
        id: 'cli-006-4', name: 'BACHOCO_SLP',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'error' }, asignacion: { status: 'success' },
          pml_mda: { status: 'pending' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'in-progress' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'error' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'success' },
        },
      },
    ],
  },
  {
    id: 'sub-008',
    code: 'C006008',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', executedBy: 'Jorge Ramírez' },
      oferta: { status: 'success', executedBy: 'Patricia Sánchez' },
      asignacion: { status: 'success', executedBy: 'Fernando Ruiz' },
      pml_mda: { status: 'success', executedBy: 'Ana Martínez' },
      pml_mtr: { status: 'success', executedBy: 'Carlos García' },
      ecd_dataset: { status: 'success', executedBy: 'Roberto Hernández' },
      ecyp: { status: 'success', executedBy: 'María López' },
      seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success', executedBy: 'Jorge Ramírez' },
      validacion: { status: 'success', executedBy: 'Patricia Sánchez' },
      vobo_mensual: { status: 'success', executedBy: 'María López' },
      revision: { status: 'in-progress' },
    },
    clients: [
      {
        id: 'cli-008-1', name: 'BIC349',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'pending' },
        },
      },
      {
        id: 'cli-008-2', name: 'BICCUAUTITLAN',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'pending' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'error' },
        },
      },
      {
        id: 'cli-008-3', name: 'RARIZPE',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-008-4', name: 'SG206',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'in-progress' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-008-5', name: 'SGOBAIN',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'pending' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
    ],
  },
  {
    id: 'sub-009',
    code: 'C006009',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 07:30', executedBy: 'Luis Mendoza' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 07:45', executedBy: 'Sandra Torres' },
      asignacion: { status: 'in-progress', lastUpdate: '2025-12-12 08:10', executedBy: 'Diego Flores' },
      pml_mda: { status: 'pending', executedBy: 'Gabriela Ríos' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 07:55', executedBy: 'Luis Mendoza' },
      ecd_dataset: { status: 'error', lastUpdate: '2025-12-12 08:00', executedBy: 'Sandra Torres' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 07:40', executedBy: 'Carlos García' },
      seg_med: { status: 'success' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'pending', executedBy: 'Diego Flores' },
      validacion: { status: 'success', lastUpdate: '2025-12-12 07:50', executedBy: 'María López' },
      vobo_mensual: { status: 'pending', executedBy: 'Ana Martínez' },
      revision: { status: 'success' },
    },
    clients: [
      {
        id: 'cli-009-1', name: 'LALA_AGS',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'error' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-009-2', name: 'HERDEZ_JAL',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'in-progress' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'in-progress' },
        },
      },
      {
        id: 'cli-009-3', name: 'MABE_QRO',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'pending' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'pending' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'pending' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'pending' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'pending' },
        },
      },
    ],
  },
  {
    id: 'sub-010',
    code: 'C006010',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'error', lastUpdate: '2025-12-12 06:30', executedBy: 'Roberto Hernández' },
      oferta: { status: 'in-progress', lastUpdate: '2025-12-12 09:00', executedBy: 'Patricia Sánchez' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 08:50', executedBy: 'Jorge Ramírez' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 08:55', executedBy: 'Luis Mendoza' },
      pml_mtr: { status: 'pending', executedBy: 'Sandra Torres' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 08:45', executedBy: 'Diego Flores' },
      ecyp: { status: 'error', lastUpdate: '2025-12-12 07:15', executedBy: 'Gabriela Ríos' },
      seg_med: { status: 'error' }, check_oferta: { status: 'error' }, tablas_mem: { status: 'in-progress', lastUpdate: '2025-12-12 09:10', executedBy: 'Carlos García' },
      validacion: { status: 'pending', executedBy: 'María López' },
      vobo_mensual: { status: 'in-progress', lastUpdate: '2025-12-12 09:20', executedBy: 'Roberto Hernández' },
      revision: { status: 'success' },
    },
    clients: [
      {
        id: 'cli-010-1', name: 'CEMEX_MTY',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'error' }, asignacion: { status: 'success' },
          pml_mda: { status: 'in-progress' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'pending' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'error' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'in-progress' },
        },
      },
      {
        id: 'cli-010-2', name: 'VITRO_SLP',
        columns: {
          medicion: { status: 'in-progress' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'in-progress' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'pending' },
        },
      },
    ],
  },
  {
    id: 'sub-011',
    code: 'C006011',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 10:00', executedBy: 'Sandra Torres' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 10:05', executedBy: 'Diego Flores' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 10:10', executedBy: 'Gabriela Ríos' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 10:15', executedBy: 'Luis Mendoza' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 10:20', executedBy: 'Patricia Sánchez' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 10:25', executedBy: 'Jorge Ramírez' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 10:30', executedBy: 'Carlos García' },
      seg_med: { status: 'success' }, check_oferta: { status: 'in-progress' }, tablas_mem: { status: 'success', lastUpdate: '2025-12-12 10:35', executedBy: 'María López' },
      validacion: { status: 'success', lastUpdate: '2025-12-12 10:40', executedBy: 'Fernando Ruiz' },
      vobo_mensual: { status: 'success', lastUpdate: '2025-12-12 10:55', executedBy: 'Sandra Torres' },
      revision: { status: 'in-progress' },
    },
    clients: [
      {
        id: 'cli-011-1', name: 'GRUMA_NLE',
        columns: {
          medicion: { status: 'pending' }, oferta: { status: 'pending' }, asignacion: { status: 'success' },
          pml_mda: { status: 'pending' }, pml_mtr: { status: 'pending' }, ecd_dataset: { status: 'pending' },
          ecyp: { status: 'success' }, seg_med: { status: 'error' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'pending' },
          validacion: { status: 'pending' },          vobo_mensual: { status: 'pending' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-011-2', name: 'ALFA_NTE',
        columns: {
          medicion: { status: 'error' }, oferta: { status: 'success' }, asignacion: { status: 'error' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'error' },
          ecyp: { status: 'success' }, seg_med: { status: 'pending' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'error' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-011-3', name: 'FEMSA_CTR',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'in-progress' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'in-progress' },
        },
      },
      {
        id: 'cli-011-4', name: 'BIMBO_SUR',
        columns: {
          medicion: { status: 'in-progress' }, oferta: { status: 'in-progress' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'in-progress' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'in-progress' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'in-progress' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'success' },
        },
      },
    ],
  },
  {
    id: 'sub-012',
    code: 'C006012',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'pending', executedBy: 'Diego Flores' },
      oferta: { status: 'pending', executedBy: 'Gabriela Ríos' },
      asignacion: { status: 'pending', executedBy: 'Luis Mendoza' },
      pml_mda: { status: 'in-progress', lastUpdate: '2025-12-12 11:00', executedBy: 'Sandra Torres' },
      pml_mtr: { status: 'in-progress', lastUpdate: '2025-12-12 11:05', executedBy: 'Carlos García' },
      ecd_dataset: { status: 'pending', executedBy: 'Patricia Sánchez' },
      ecyp: { status: 'pending', executedBy: 'Jorge Ramírez' },
      seg_med: { status: 'pending' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'pending', executedBy: 'Diego Flores' },
      validacion: { status: 'pending', executedBy: 'Gabriela Ríos' },
      vobo_mensual: { status: 'pending', executedBy: 'Fernando Ruiz' },
      revision: { status: 'error' },
    },
    clients: [
      {
        id: 'cli-012-1', name: 'PEMEX_OCC',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'error' }, asignacion: { status: 'success' },
          pml_mda: { status: 'pending' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'in-progress' },
          ecyp: { status: 'success' }, seg_med: { status: 'pending' }, check_oferta: { status: 'error' }, tablas_mem: { status: 'error' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'pending' },
        },
      },
      {
        id: 'cli-012-2', name: 'TELMEX_NTE',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'error' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'in-progress' },
        },
      },
      {
        id: 'cli-012-3', name: 'SORIANA_PTE',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'in-progress' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'in-progress' },
        },
      },
    ],
  },
  {
    id: 'sub-013',
    code: 'C006013',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 09:00', executedBy: 'Gabriela Ríos' },
      oferta: { status: 'error', lastUpdate: '2025-12-12 08:30', executedBy: 'Luis Mendoza' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 09:05', executedBy: 'Sandra Torres' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 09:10', executedBy: 'Diego Flores' },
      pml_mtr: { status: 'in-progress', lastUpdate: '2025-12-12 09:40', executedBy: 'Roberto Hernández' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 09:15', executedBy: 'Patricia Sánchez' },
      ecyp: { status: 'pending', executedBy: 'Jorge Ramírez' },
      seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success', lastUpdate: '2025-12-12 09:20', executedBy: 'Ana Martínez' },
      validacion: { status: 'error', lastUpdate: '2025-12-12 08:15', executedBy: 'Carlos García' },
      vobo_mensual: { status: 'success', lastUpdate: '2025-12-12 09:30', executedBy: 'Gabriela Ríos' },
      revision: { status: 'pending' },
    },
    clients: [
      {
        id: 'cli-013-1', name: 'MODELO_BCS',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'pending' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'pending' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'pending' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-013-2', name: 'COPPEL_CHI',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'error' }, asignacion: { status: 'success' },
          pml_mda: { status: 'in-progress' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'pending' }, seg_med: { status: 'error' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'error' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'success' },
        },
      },
    ],
  },
  {
    id: 'sub-014',
    code: 'C006014',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 11:00', executedBy: 'Ana Martínez' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 11:05', executedBy: 'Roberto Hernández' },
      asignacion: { status: 'error', lastUpdate: '2025-12-12 10:20', executedBy: 'Fernando Ruiz' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 11:10', executedBy: 'Patricia Sánchez' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 11:15', executedBy: 'Jorge Ramírez' },
      ecd_dataset: { status: 'in-progress', lastUpdate: '2025-12-12 11:30', executedBy: 'Luis Mendoza' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 11:20', executedBy: 'Sandra Torres' },
      seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success', lastUpdate: '2025-12-12 11:25', executedBy: 'Diego Flores' },
      validacion: { status: 'success', lastUpdate: '2025-12-12 11:30', executedBy: 'Gabriela Ríos' },
      vobo_mensual: { status: 'success', lastUpdate: '2025-12-12 11:40', executedBy: 'Ana Martínez' },
      revision: { status: 'success' },
    },
    clients: [
      {
        id: 'cli-014-1', name: 'BACHOCO_SLP',
        columns: {
          medicion: { status: 'in-progress' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'in-progress' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'in-progress' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'error' },
        },
      },
      {
        id: 'cli-014-2', name: 'LALA_AGS',
        columns: {
          medicion: { status: 'pending' }, oferta: { status: 'pending' }, asignacion: { status: 'success' },
          pml_mda: { status: 'pending' }, pml_mtr: { status: 'pending' }, ecd_dataset: { status: 'pending' },
          ecyp: { status: 'success' }, seg_med: { status: 'in-progress' }, check_oferta: { status: 'error' }, tablas_mem: { status: 'pending' },
          validacion: { status: 'pending' },          vobo_mensual: { status: 'pending' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-014-3', name: 'HERDEZ_JAL',
        columns: {
          medicion: { status: 'error' }, oferta: { status: 'success' }, asignacion: { status: 'error' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'error' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'error' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
    ],
  },
  {
    id: 'sub-015',
    code: 'C006015',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'in-progress', lastUpdate: '2025-12-12 10:30', executedBy: 'Carlos García' },
      oferta: { status: 'pending', executedBy: 'María López' },
      asignacion: { status: 'in-progress', lastUpdate: '2025-12-12 10:35', executedBy: 'Fernando Ruiz' },
      pml_mda: { status: 'error', lastUpdate: '2025-12-12 09:50', executedBy: 'Ana Martínez' },
      pml_mtr: { status: 'pending', executedBy: 'Roberto Hernández' },
      ecd_dataset: { status: 'in-progress', lastUpdate: '2025-12-12 10:40', executedBy: 'Patricia Sánchez' },
      ecyp: { status: 'pending', executedBy: 'Jorge Ramírez' },
      seg_med: { status: 'pending' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'error', lastUpdate: '2025-12-12 09:30', executedBy: 'Luis Mendoza' },
      validacion: { status: 'pending', executedBy: 'Sandra Torres' },
      vobo_mensual: { status: 'error', lastUpdate: '2025-12-12 09:15', executedBy: 'Carlos García' },
      revision: { status: 'success' },
    },
    clients: [
      {
        id: 'cli-015-1', name: 'MABE_QRO',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-015-2', name: 'CEMEX_MTY',
        columns: {
          medicion: { status: 'in-progress' }, oferta: { status: 'in-progress' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'in-progress' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'in-progress' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'in-progress' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-015-3', name: 'VITRO_SLP',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'error' }, asignacion: { status: 'success' },
          pml_mda: { status: 'pending' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'in-progress' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'in-progress' }, tablas_mem: { status: 'error' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-015-4', name: 'GRUMA_NLE',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'error' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'error' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'pending' },
        },
      },
    ],
  },
  {
    id: 'sub-016',
    code: 'C006016',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 08:00', executedBy: 'Sandra Torres' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 08:05', executedBy: 'Diego Flores' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 08:10', executedBy: 'Gabriela Ríos' },
      pml_mda: { status: 'in-progress', lastUpdate: '2025-12-12 08:40', executedBy: 'Luis Mendoza' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 08:15', executedBy: 'Ana Martínez' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 08:20', executedBy: 'Roberto Hernández' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 08:25', executedBy: 'Fernando Ruiz' },
      seg_med: { status: 'pending' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success', lastUpdate: '2025-12-12 08:30', executedBy: 'Patricia Sánchez' },
      validacion: { status: 'in-progress', lastUpdate: '2025-12-12 08:45', executedBy: 'Jorge Ramírez' },
      vobo_mensual: { status: 'success', lastUpdate: '2025-12-12 08:42', executedBy: 'Sandra Torres' },
      revision: { status: 'success' },
    },
    clients: [
      {
        id: 'cli-016-1', name: 'ALFA_NTE',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'in-progress' }, check_oferta: { status: 'error' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'error' },
        },
      },
      {
        id: 'cli-016-2', name: 'FEMSA_CTR',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'pending' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'pending' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'pending' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
    ],
  },
  {
    id: 'sub-017',
    code: 'C006017',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 07:00', executedBy: 'Jorge Ramírez' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 07:05', executedBy: 'Carlos García' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 07:10', executedBy: 'María López' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 07:15', executedBy: 'Fernando Ruiz' },
      pml_mtr: { status: 'error', lastUpdate: '2025-12-12 06:45', executedBy: 'Ana Martínez' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 07:20', executedBy: 'Roberto Hernández' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 07:25', executedBy: 'Patricia Sánchez' },
      seg_med: { status: 'pending' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success', lastUpdate: '2025-12-12 07:30', executedBy: 'Luis Mendoza' },
      validacion: { status: 'success', lastUpdate: '2025-12-12 07:35', executedBy: 'Sandra Torres' },
      vobo_mensual: { status: 'success', lastUpdate: '2025-12-12 07:50', executedBy: 'Jorge Ramírez' },
      revision: { status: 'success' },
    },
    clients: [
      {
        id: 'cli-017-1', name: 'BIMBO_SUR',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'error' }, asignacion: { status: 'success' },
          pml_mda: { status: 'in-progress' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'pending' }, seg_med: { status: 'error' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'error' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-017-2', name: 'PEMEX_OCC',
        columns: {
          medicion: { status: 'in-progress' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'in-progress' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'error' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-017-3', name: 'TELMEX_NTE',
        columns: {
          medicion: { status: 'pending' }, oferta: { status: 'pending' }, asignacion: { status: 'success' },
          pml_mda: { status: 'pending' }, pml_mtr: { status: 'pending' }, ecd_dataset: { status: 'pending' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'pending' },
          validacion: { status: 'pending' },          vobo_mensual: { status: 'pending' },
          revision: { status: 'error' },
        },
      },
    ],
  },
  {
    id: 'sub-018',
    code: 'C006018',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'error', lastUpdate: '2025-12-12 06:00', executedBy: 'Diego Flores' },
      oferta: { status: 'error', lastUpdate: '2025-12-12 06:10', executedBy: 'Gabriela Ríos' },
      asignacion: { status: 'pending', executedBy: 'Luis Mendoza' },
      pml_mda: { status: 'pending', executedBy: 'Sandra Torres' },
      pml_mtr: { status: 'pending', executedBy: 'Carlos García' },
      ecd_dataset: { status: 'pending', executedBy: 'María López' },
      ecyp: { status: 'pending', executedBy: 'Fernando Ruiz' },
      seg_med: { status: 'success' }, check_oferta: { status: 'in-progress' }, tablas_mem: { status: 'pending', executedBy: 'Ana Martínez' },
      validacion: { status: 'pending', executedBy: 'Roberto Hernández' },
      vobo_mensual: { status: 'pending', executedBy: 'Diego Flores' },
      revision: { status: 'success' },
    },
    clients: [
      {
        id: 'cli-018-1', name: 'SORIANA_PTE',
        columns: {
          medicion: { status: 'error' }, oferta: { status: 'success' }, asignacion: { status: 'error' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'error' },
          ecyp: { status: 'success' }, seg_med: { status: 'error' }, check_oferta: { status: 'error' }, tablas_mem: { status: 'success' },
          validacion: { status: 'error' },          vobo_mensual: { status: 'success' },
          revision: { status: 'pending' },
        },
      },
      {
        id: 'cli-018-2', name: 'MODELO_BCS',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'in-progress' },
        },
      },
      {
        id: 'cli-018-3', name: 'COPPEL_CHI',
        columns: {
          medicion: { status: 'in-progress' }, oferta: { status: 'in-progress' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'in-progress' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'in-progress' }, seg_med: { status: 'error' }, check_oferta: { status: 'in-progress' }, tablas_mem: { status: 'success' },
          validacion: { status: 'in-progress' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-018-4', name: 'BACHOCO_SLP',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'error' }, asignacion: { status: 'success' },
          pml_mda: { status: 'pending' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'in-progress' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'error' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'error' },
        },
      },
    ],
  },
  {
    id: 'sub-019',
    code: 'C006019',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 09:30', executedBy: 'Luis Mendoza' },
      oferta: { status: 'in-progress', lastUpdate: '2025-12-12 10:00', executedBy: 'Sandra Torres' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 09:35', executedBy: 'Diego Flores' },
      pml_mda: { status: 'success', lastUpdate: '2025-12-12 09:40', executedBy: 'Gabriela Ríos' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 09:45', executedBy: 'Ana Martínez' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 09:50', executedBy: 'Roberto Hernández' },
      ecyp: { status: 'in-progress', lastUpdate: '2025-12-12 10:05', executedBy: 'Fernando Ruiz' },
      seg_med: { status: 'success' }, check_oferta: { status: 'error' }, tablas_mem: { status: 'success', lastUpdate: '2025-12-12 09:55', executedBy: 'Patricia Sánchez' },
      validacion: { status: 'success', lastUpdate: '2025-12-12 10:00', executedBy: 'Jorge Ramírez' },
      vobo_mensual: { status: 'pending', executedBy: 'Luis Mendoza' },
      revision: { status: 'pending' },
    },
    clients: [
      {
        id: 'cli-019-1', name: 'LALA_AGS',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'error' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'error' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'pending' },
        },
      },
      {
        id: 'cli-019-2', name: 'HERDEZ_JAL',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'pending' },
        },
      },
      {
        id: 'cli-019-3', name: 'MABE_QRO',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'pending' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'pending' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'error' }, tablas_mem: { status: 'pending' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
    ],
  },
  {
    id: 'sub-020',
    code: 'C006020',
    isExpanded: false,
    isSelected: false,
    columns: {
      medicion: { status: 'success', lastUpdate: '2025-12-12 11:30', executedBy: 'Gabriela Ríos' },
      oferta: { status: 'success', lastUpdate: '2025-12-12 11:35', executedBy: 'Luis Mendoza' },
      asignacion: { status: 'success', lastUpdate: '2025-12-12 11:40', executedBy: 'Sandra Torres' },
      pml_mda: { status: 'error', lastUpdate: '2025-12-12 11:00', executedBy: 'Diego Flores' },
      pml_mtr: { status: 'success', lastUpdate: '2025-12-12 11:45', executedBy: 'Carlos García' },
      ecd_dataset: { status: 'success', lastUpdate: '2025-12-12 11:50', executedBy: 'María López' },
      ecyp: { status: 'success', lastUpdate: '2025-12-12 11:55', executedBy: 'Fernando Ruiz' },
      seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'in-progress', lastUpdate: '2025-12-12 12:00', executedBy: 'Ana Martínez' },
      validacion: { status: 'success', lastUpdate: '2025-12-12 12:05', executedBy: 'Roberto Hernández' },
      vobo_mensual: { status: 'success', lastUpdate: '2025-12-12 12:15', executedBy: 'Gabriela Ríos' },
      revision: { status: 'success' },
    },
    clients: [
      {
        id: 'cli-020-1', name: 'CEMEX_MTY',
        columns: {
          medicion: { status: 'success' }, oferta: { status: 'error' }, asignacion: { status: 'success' },
          pml_mda: { status: 'in-progress' }, pml_mtr: { status: 'success' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'pending' }, seg_med: { status: 'pending' }, check_oferta: { status: 'pending' }, tablas_mem: { status: 'success' },
          validacion: { status: 'error' },          vobo_mensual: { status: 'in-progress' },
          revision: { status: 'success' },
        },
      },
      {
        id: 'cli-020-2', name: 'VITRO_SLP',
        columns: {
          medicion: { status: 'in-progress' }, oferta: { status: 'success' }, asignacion: { status: 'success' },
          pml_mda: { status: 'success' }, pml_mtr: { status: 'in-progress' }, ecd_dataset: { status: 'success' },
          ecyp: { status: 'success' }, seg_med: { status: 'success' }, check_oferta: { status: 'success' }, tablas_mem: { status: 'success' },
          validacion: { status: 'success' },          vobo_mensual: { status: 'success' },
          revision: { status: 'success' },
        },
      },
    ],
  },
];

export const mockSeparacionECDData: SeparacionECDData = {
  startDate: '12/02/2026',
  endDate: '12/02/2026',
  progress: 65,
  subcuentas: mockSubcuentas,
};

export const procesColumns = [
  { id: 'medicion', label: 'Medición' },
  { id: 'oferta', label: 'Oferta' },
  { id: 'asignacion', label: 'Asignación MDA' },
  { id: 'pml_mda', label: 'PML MDA' },
  { id: 'pml_mtr', label: 'PML MTR' },
  { id: 'ecd_dataset', label: 'ECD Dataset' },
  { id: 'ecyp', label: 'ECyP' },
  { id: 'seg_med', label: 'Seg. de Med.' },
  { id: 'check_oferta', label: 'Check Oferta' },
  { id: 'tablas_mem', label: 'Calcular Tablas MEM' },
  { id: 'validacion', label: 'Check de ECyP' },
  { id: 'vobo_mensual', label: 'VoBo Mensual de Med.' },
  { id: 'revision', label: 'Revisión' },
];

export const columnGroups = [
  { label: 'Carga de Datos', colspan: 7 },
  { label: 'Ejecuciones', colspan: 3 },
  { label: 'Validación', colspan: 2 },
  { label: 'Revisión', colspan: 1 },
];

// Indices where a group separator should appear BEFORE the column
export const groupSeparatorIndices = new Set([7, 10, 12]);
